"""empty message

Revision ID: 3f25ec815dd2
Revises: 
Create Date: 2019-04-11 20:39:09.934895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f25ec815dd2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('console', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wager', sa.Integer(), nullable=False),
    sa.Column('winner', sa.String(length=80), nullable=True),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('user_one', sa.Integer(), nullable=False),
    sa.Column('user_two', sa.Integer(), nullable=True),
    sa.Column('game', sa.Integer(), nullable=False),
    sa.Column('user_one_stop', sa.Boolean(), nullable=True),
    sa.Column('user_two_stop', sa.Boolean(), nullable=True),
    sa.Column('user_one_aproval', sa.Boolean(), nullable=True),
    sa.Column('user_two_aproval', sa.Boolean(), nullable=True),
    sa.Column('final_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_one'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('winner')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    op.drop_table('user')
    op.drop_table('games')
    # ### end Alembic commands ###
